# Generated by Django 5.1.15 on 2026-04-12 17:45

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cash_balance",
                    models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=16),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("thesis", models.TextField(blank=True, default="")),
                ("thesis_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_weight_pct",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="positions.account",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="core.sector",
                    ),
                ),
                (
                    "themes",
                    models.ManyToManyField(blank=True, related_name="positions", to="core.theme"),
                ),
            ],
            options={
                "ordering": ["symbol"],
                "unique_together": {("symbol", "account")},
            },
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shares", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=4, max_digits=14),
                ),
                ("purchase_date", models.DateField()),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date"],
            },
        ),
    ]
