# Generated by Django 5.1.15 on 2026-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="bear_case",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="position",
            name="bear_case_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
