# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_auto_20171029_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cash_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='cost_basis',
            field=models.FloatField(default=0.0),
        ),
    ]
