# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-24 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_auto_20171029_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='shares',
            field=models.FloatField(),
        ),
    ]
