# Generated by Django 5.1.15 on 2026-04-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_of", models.DateField(unique=True)),
                ("portfolio_snapshot", models.JSONField()),
                ("response", models.TextField()),
                ("model", models.CharField(default="claude-opus-4-6", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-week_of"],
            },
        ),
        migrations.CreateModel(
            name="ThesisCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thesis_snapshot", models.TextField()),
                (
                    "price_snapshot",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
                ),
                ("response", models.TextField()),
                ("model", models.CharField(default="claude-opus-4-6", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thesis_checks",
                        to="positions.position",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
